# Generated by Django 5.1.3 on 2024-11-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0003_alter_loan_control_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentsched', to='mcoop_app.paymentschedule'),
        ),
    ]
