# Generated by Django 5.1.3 on 2024-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
