# Generated by Django 4.2.1 on 2024-11-27 16:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0004_alter_payment_payment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved')], default='Approved', max_length=50),
        ),
    ]
