# Generated by Django 4.2.1 on 2024-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0006_loan_annual_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='service_fee_component',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
