# Generated by Django 5.1.1 on 2024-09-26 21:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('control_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_type', models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency')], default='Regular', max_length=10)),
                ('loan_period', models.PositiveIntegerField()),
                ('loan_period_unit', models.CharField(choices=[('Months', 'Months'), ('Years', 'Years')], default='Months', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Paid', 'Paid')], max_length=10)),
                ('purpose', models.CharField(choices=[('Education', 'Education'), ('Medical/Emergency', 'Medical/Emergency'), ('House Construction & Repair', 'House Construction & Repair'), ('Commodity/Appliances', 'Commodity/Appliances'), ('Utility Services', 'Utility Services'), ('Others', 'Others')], default='Choose Purpose', max_length=200)),
                ('others_purpose', models.CharField(blank=True, max_length=200)),
                ('nameOfSpouse', models.CharField(blank=True, default='If applicable', max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpsucoop_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.TextField(blank=True, default='Not Provided')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_by_id', to='mpsucoop_app.member'),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpsucoop_app.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('OR', models.CharField(default='DEFAULT_Payment_NUMBER', max_length=50, primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], default='Unknown', max_length=50)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notarial_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('admin_cost', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('cisp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpsucoop_app.loan')),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mpsucoop_app.paymentschedule')),
            ],
        ),
    ]
