# Generated by Django 5.1.1 on 2024-09-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsucoop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='notarial_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='loan',
            name='take_home_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
