# Generated by Django 5.1.1 on 2024-09-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsucoop_app', '0002_loan_notarial_fee_loan_take_home_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Loan', 'Loan Disbursal'), ('Payment', 'Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpsucoop_app.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='mpsucoop_app.member')),
            ],
            options={
                'ordering': ['transaction_date'],
            },
        ),
    ]
