# Generated by Django 5.1.1 on 2024-09-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpsucoop_app', '0003_ledger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='shareCapital',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
    ]
